class TanukiSubtitlerVals:
    def exclusions():
        exclude = []
        exclude.append("。")
        exclude.append("、")
        exclude.append("だ")
        exclude.append("は")
        exclude.append("た")
        exclude.append("て")
        exclude.append("に")
        exclude.append("か")
        exclude.append("が")
        exclude.append("？")
        exclude.append("で")
        exclude.append("や")
        exclude.append("・")
        exclude.append("の")
        exclude.append("な")
        exclude.append("を")
        exclude.append("と")
        exclude.append("よ")
        exclude.append("！")
        exclude.append("お")
        exclude.append("あ")
        exclude.append("てる")
        exclude.append("ぬ")
        exclude.append("え")